name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  integration-test:
    name: Integration tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          cd testing
          make test
      - name: clean
        run: |
          cd testing
          make clean
  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ steps.rust-toolchain.outputs.cachekey }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests
        id: test
        run: cargo llvm-cov --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true
      - name: End test
        run: '[ "${{ steps.test.outcome }}" = "success" ]'
